// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: ae6f9fe586528b594671037eb8d003d4c5a72753e2d2939c445bc0ad2251a4d1

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "Mindtech";

export const themeNames: ThemeName[] = ["Mindtech"];

export type KcEnvName = "BACKGROUND_LOGO_URL";

export const kcEnvNames: KcEnvName[] = ["BACKGROUND_LOGO_URL"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    BACKGROUND_LOGO_URL: ""
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
